language: swift
osx_image: xcode11.2
script:
  - xcodebuild -scheme SwiftCalculator -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
